/*
 * Hilmi Abdurrahman Fakhrudin - 1807422008
 */
package hilmi;

import static java.awt.image.ImageObserver.ERROR;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hilmi
 */
public class Battle_Item_Select extends javax.swing.JFrame {
    
    DBAksess dbakses = new DBAksess();
    Battle_Campaign_Action_Normal bcam;
    
    String[] selectedItem;
    String usereID;
    
    
    
    /**
     * Creates new form Battle_Item_Select
     */
    public Battle_Item_Select(Battle_Campaign_Action_Normal bcam, String userID) {
        initComponents();
        this.usereID = userID;
        if (userID.equals("-1")) {
            JOptionPane.showMessageDialog(this, "Cannot Start This Window Directly!\nClosing Program", "Error!", JOptionPane.ERROR_MESSAGE);
            this.dispose();
            System.exit(0);
        }
        this.bcam = bcam;
        getData();
    }
    
    private void getData(){
        try {
            itemListTbl.setModel(dbakses.getTableData("list_inventory", "user_id", usereID));
            
            itemListTbl.getColumnModel().getColumn(0).setWidth(0);
            itemListTbl.getColumnModel().getColumn(0).setMinWidth(0);
            itemListTbl.getColumnModel().getColumn(0).setMaxWidth(0);
            
            for (int i = 2; i < itemListTbl.getModel().getColumnCount(); i++) {
                itemListTbl.getColumnModel().getColumn(i).setWidth(0);
                itemListTbl.getColumnModel().getColumn(i).setMinWidth(0);
                itemListTbl.getColumnModel().getColumn(i).setMaxWidth(0);
            }
            selectedItem = new String[itemListTbl.getModel().getColumnCount()];
            itemListTbl.setRowSelectionInterval(0, 0);
            setItem(0);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error!\n" + e, "Error", ERROR);
        }
    }
    
    private void setItem(int rowNum){
        itemName.setText(itemListTbl.getValueAt(rowNum, 1).toString());
        itemEffectValue.setText(itemListTbl.getValueAt(rowNum, 3).toString());
        itemQty.setText(itemListTbl.getValueAt(rowNum, 6).toString());
        itemDescription.setText(itemListTbl.getValueAt(rowNum, 5).toString());
        
        
        for (int i = 0; i < itemListTbl.getColumnCount(); i++) {
            selectedItem[i] = itemListTbl.getValueAt(rowNum, i).toString();
        }
        
//        itemIcon.setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("monsterIcon/"+monsterID+".png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        itemListTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        itemQty = new javax.swing.JLabel();
        itemEffectValue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        itemName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemDescription = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        useItem = new javax.swing.JButton();
        itemIcon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Item");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(580, 450));
        setMinimumSize(new java.awt.Dimension(580, 450));
        setPreferredSize(new java.awt.Dimension(580, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemListTbl.setBackground(new java.awt.Color(0, 0, 0));
        itemListTbl.setForeground(new java.awt.Color(255, 255, 255));
        itemListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        itemListTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemListTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemListTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 290));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Item to Use");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 510, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Qty:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        itemQty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemQty.setForeground(new java.awt.Color(255, 255, 255));
        itemQty.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemQty.setText("jLabel4");
        getContentPane().add(itemQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 90, -1));

        itemEffectValue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemEffectValue.setForeground(new java.awt.Color(255, 255, 255));
        itemEffectValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemEffectValue.setText("jLabel4");
        getContentPane().add(itemEffectValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Effect Value:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        itemName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemName.setForeground(new java.awt.Color(255, 255, 255));
        itemName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemName.setText("jLabel4");
        getContentPane().add(itemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 90, -1));

        itemDescription.setEditable(false);
        itemDescription.setBackground(new java.awt.Color(0, 0, 0));
        itemDescription.setColumns(20);
        itemDescription.setForeground(new java.awt.Color(255, 255, 255));
        itemDescription.setLineWrap(true);
        itemDescription.setRows(5);
        itemDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane2.setViewportView(itemDescription);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 270, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Description:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        cancelBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 80, 30));

        useItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        useItem.setText("Use!");
        useItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useItemActionPerformed(evt);
            }
        });
        getContentPane().add(useItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 80, 30));

        itemIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemIcon.setMaximumSize(new java.awt.Dimension(75, 75));
        itemIcon.setMinimumSize(new java.awt.Dimension(75, 75));
        itemIcon.setPreferredSize(new java.awt.Dimension(75, 75));
        getContentPane().add(itemIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/3@300px.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void itemListTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListTblMouseClicked
        setItem(itemListTbl.getSelectedRow());
    }//GEN-LAST:event_itemListTblMouseClicked

    private void useItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useItemActionPerformed
        bcam.useItem(selectedItem[1], selectedItem[2], Integer.parseInt(selectedItem[3]));
        dbakses.reduceItem(usereID, selectedItem[0], Integer.parseInt(selectedItem[6]));
        this.dispose();
    }//GEN-LAST:event_useItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Battle_Item_Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Battle_Item_Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Battle_Item_Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Battle_Item_Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Battle_Item_Select(null, "-1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextArea itemDescription;
    private javax.swing.JLabel itemEffectValue;
    private javax.swing.JLabel itemIcon;
    private javax.swing.JTable itemListTbl;
    private javax.swing.JLabel itemName;
    private javax.swing.JLabel itemQty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton useItem;
    // End of variables declaration//GEN-END:variables
}
