/*
 * Hilmi Abdurrahman Fakhrudin - 1807422008
 */
package hilmi;

import static java.awt.image.ImageObserver.ERROR;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hilmi
 */
public class Battle_Online_Select_Opponent extends javax.swing.JPanel {

    private DBAksess dbakses = new DBAksess();
    private BattleMainFrame mf;
    private String[] selectedOpponent;
    private String selectedOpponentID = "";
    private String[][] opponentLineUp;

    /**
     * Creates new form Battle_Online_Select_Opponent
     */
    public Battle_Online_Select_Opponent(BattleMainFrame mf) {
        initComponents();
        this.mf = mf;
        getPartyList();
    }

    private void getPartyList() {
        try {
            opponentTable.setModel(dbakses.getOpponentDataTable(mf.getPlayer().getId()));
            for (int i = 0; i < 13; i++) {
                opponentTable.getColumnModel().getColumn(i).setWidth(0);
                opponentTable.getColumnModel().getColumn(i).setMinWidth(0);
                opponentTable.getColumnModel().getColumn(i).setMaxWidth(0);
            }
            for (int i = 14; i < opponentTable.getModel().getColumnCount(); i++) {
                opponentTable.getColumnModel().getColumn(i).setWidth(0);
                opponentTable.getColumnModel().getColumn(i).setMinWidth(0);
                opponentTable.getColumnModel().getColumn(i).setMaxWidth(0);
            }
            opponentTable.setRowSelectionInterval(0, 0);
            setItem(0);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error!\n" + e, "Error", ERROR);
        }
    }

    private void setItem(int rowNum) {
        selectedOpponentID = opponentTable.getValueAt(rowNum, 12).toString();
        opponentName.setText(opponentTable.getValueAt(rowNum, 13).toString());
        selectedOpponent = new String[opponentTable.getColumnCount()];
        
        for (int i = 0; i < opponentTable.getColumnCount(); i++) {
            selectedOpponent[i] = opponentTable.getValueAt(rowNum, i).toString();
        }
        
        try {
            opponentLineUp = dbakses.getOpponentPublicLineup(selectedOpponentID);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error!\n" + e, "Error", ERROR);
        }
        
        javax.swing.JLabel[] monIcon = {monsterIcon1, monsterIcon2, monsterIcon3};
        javax.swing.JLabel[] monLabel = {monsterName1, monsterName2, monsterName3};
        
        for (int i = 0; i < monIcon.length; i++) {
            monIcon[i].setVisible(false);
            monLabel[i].setVisible(false);
        }
        
        for (int i = 0; i < opponentLineUp.length; i++) {
                monIcon[i].setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("monsterIcon/"+opponentLineUp[i][3]+".png")));
                monLabel[i].setText(opponentLineUp[i][2]);
                monIcon[i].setVisible(true);
                monLabel[i].setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        opponentTable = new javax.swing.JTable();
        monsterIcon3 = new javax.swing.JLabel();
        monsterIcon1 = new javax.swing.JLabel();
        monsterIcon2 = new javax.swing.JLabel();
        monsterName3 = new javax.swing.JLabel();
        monsterName1 = new javax.swing.JLabel();
        monsterName2 = new javax.swing.JLabel();
        challangeBtn = new javax.swing.JButton();
        opponentName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(820, 430));
        setMinimumSize(new java.awt.Dimension(820, 430));
        setName(""); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opponentTable.setBackground(new java.awt.Color(0, 0, 0));
        opponentTable.setForeground(new java.awt.Color(255, 255, 255));
        opponentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        opponentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opponentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(opponentTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 89, 312, 330));

        monsterIcon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monsterIcon3.setText("monsterIcon");
        monsterIcon3.setMaximumSize(new java.awt.Dimension(100, 100));
        monsterIcon3.setMinimumSize(new java.awt.Dimension(100, 100));
        monsterIcon3.setOpaque(true);
        monsterIcon3.setPreferredSize(new java.awt.Dimension(100, 100));
        add(monsterIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, -1, -1));

        monsterIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monsterIcon1.setText("monsterIcon");
        monsterIcon1.setMaximumSize(new java.awt.Dimension(100, 100));
        monsterIcon1.setMinimumSize(new java.awt.Dimension(100, 100));
        monsterIcon1.setOpaque(true);
        monsterIcon1.setPreferredSize(new java.awt.Dimension(100, 100));
        add(monsterIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        monsterIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monsterIcon2.setText("monsterIcon");
        monsterIcon2.setMaximumSize(new java.awt.Dimension(100, 100));
        monsterIcon2.setMinimumSize(new java.awt.Dimension(100, 100));
        monsterIcon2.setOpaque(true);
        monsterIcon2.setPreferredSize(new java.awt.Dimension(100, 100));
        add(monsterIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        monsterName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monsterName3.setText("Monster Name");
        add(monsterName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 100, -1));

        monsterName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monsterName1.setText("Monster Name");
        add(monsterName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 100, -1));

        monsterName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monsterName2.setText("Monster Name");
        add(monsterName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 100, -1));

        challangeBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        challangeBtn.setText("Challange!");
        challangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                challangeBtnActionPerformed(evt);
            }
        });
        add(challangeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 150, 50));

        opponentName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        opponentName.setForeground(new java.awt.Color(255, 255, 255));
        opponentName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        opponentName.setText("opName");
        add(opponentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 450, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Opponent Monster:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Select Opponent");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 480, 40));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 470, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/3@300px.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 830, 430));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        mf.runBattleMenu();
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void opponentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opponentTableMouseClicked
        setItem(opponentTable.getSelectedRow());
    }//GEN-LAST:event_opponentTableMouseClicked

    private void challangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_challangeBtnActionPerformed
        mf.runOnlineBattleSelectParty(selectedOpponent, opponentLineUp);
        this.setVisible(false);
    }//GEN-LAST:event_challangeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton challangeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel monsterIcon1;
    private javax.swing.JLabel monsterIcon2;
    private javax.swing.JLabel monsterIcon3;
    private javax.swing.JLabel monsterName1;
    private javax.swing.JLabel monsterName2;
    private javax.swing.JLabel monsterName3;
    private javax.swing.JLabel opponentName;
    private javax.swing.JTable opponentTable;
    // End of variables declaration//GEN-END:variables
}
