/*
 * Hilmi Abdurrahman Fakhrudin - 1807422008
 */
package hilmi;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hilmi
 */
public class Battle_Menu_Panel extends javax.swing.JPanel {

    BattleMainFrame mf;

    /**
     * Creates new form Battle_Menu_Panel
     */
    public Battle_Menu_Panel(BattleMainFrame mf) {
        initComponents();
        this.mf = mf;
        campaignButton.setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("uiIcon/CampaignIcon.png")));
        onlineButton.setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("uiIcon/GlobalVSIcon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        onlineButton = new javax.swing.JButton();
        campaignButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(848, 480));
        setMinimumSize(new java.awt.Dimension(848, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 80, 40));

        onlineButton.setBackground(new java.awt.Color(51, 51, 51));
        onlineButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        onlineButton.setForeground(new java.awt.Color(255, 255, 255));
        onlineButton.setText("Global V.S.");
        onlineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineButtonActionPerformed(evt);
            }
        });
        add(onlineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 290, 110));

        campaignButton.setBackground(new java.awt.Color(51, 51, 51));
        campaignButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campaignButton.setForeground(new java.awt.Color(255, 255, 255));
        campaignButton.setText("Campaign");
        campaignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campaignButtonActionPerformed(evt);
            }
        });
        add(campaignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 290, 110));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Mode");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/3@300px.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 850, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void campaignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campaignButtonActionPerformed
        mf.runCampaignLvlSelect();
        this.setVisible(false);
    }//GEN-LAST:event_campaignButtonActionPerformed

    private void onlineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlineButtonActionPerformed
        DBAksess db = new DBAksess();
        if (db.checkOnlineOpponent(mf.getPlayer().getId())) {
            mf.runOnlineBattleMatchMaking();
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "No opponent available!");
        }
    }//GEN-LAST:event_onlineButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        mf.getMainMenu().setVisible(true);
        mf.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton campaignButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton onlineButton;
    // End of variables declaration//GEN-END:variables
}
