/*
 * Hilmi Abdurrahman Fakhrudin - 1807422008
 */
package hilmi;

import iskandar.*;
import javax.swing.JOptionPane;
/**
 *
 * @author hilmi
 */
public class BattleMainFrame extends javax.swing.JFrame {
    
    private Battle_Campaign_PartySelect_Panel partySelect;
    private Battle_Menu_Panel BattleMenu;
    private Battle_Campaign_LvlSelect_Panel campaignLvlSelect;
    private Battle_Campaign_Action_Normal bcam;
    private Battle_Online_Select_Opponent boso;
    MainMenu mainMenu;
    
    DBAksess db = new DBAksess();
    
    /**
     * Creates new form TestMainFrame
     */
    public BattleMainFrame(){
        JOptionPane.showMessageDialog(this, "Cannot Run Directly\nQuitting!");
        System.exit(0);
    }
    
    public BattleMainFrame(MainMenu mm) {
        initComponents(); 
        mainMenu = mm;
        if (db.checkPartyAvailable(mm.getPlayer().getId())) {
            runBattleMenu();
        } else {
            JOptionPane.showMessageDialog(this, "You didn't have any monster!");
            mm.setVisible(true);
            this.dispose();
        }
        
    }
    
    public Player getPlayer(){
        return mainMenu.getPlayer();
    }

    public MainMenu getMainMenu() {
        return mainMenu;
    }
    
    public void runBattleMenu(){
        BattleMenu = new Battle_Menu_Panel(this);
        add(BattleMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }
    
    public void runCampaignLvlSelect(){
        campaignLvlSelect = new Battle_Campaign_LvlSelect_Panel(this);
        add(campaignLvlSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }
    
    public void runBattleCampaignPartySelect(int lvl){
        partySelect = new Battle_Campaign_PartySelect_Panel(this, lvl, null, null);
        add(partySelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }
    
    public void runBattleAction(Battle_Campaign_Action_Normal bcamIn){
        this.bcam = bcamIn;
        add(bcam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }
    
    public void runOnlineBattleMatchMaking(){
        this.boso = new Battle_Online_Select_Opponent(this);
        add(boso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }
    
    public void runOnlineBattleSelectParty(String[] opponentData, String[][] opponentLineUp){
        partySelect = new Battle_Campaign_PartySelect_Panel(this, -1, opponentData, opponentLineUp);
        add(partySelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monster Spirit");
        setMaximumSize(new java.awt.Dimension(848, 480));
        setMinimumSize(new java.awt.Dimension(848, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattleMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattleMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattleMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattleMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
