/*
 * Hilmi Abdurrahman Fakhrudin - 1807422008
 */
package hilmi;

import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import com.ish.monsterspirit.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import septian.*;

/**
 *
 * @author hilmi
 */
public class SelectMonsterFrame extends javax.swing.JFrame {

    private Party_Data pd;
    private DBAksess dbakses = new DBAksess();
    private String[] selectedParty;
    private DBAksess dba = new DBAksess();
    private DBUtils dbu = new DBUtils();
    private String userID;
    private CharPane cp;
    private publicLineupPanel plp;//= new publicLineupPanel();

    /**
     * Creates new form SelectMonsterFrame
     */
    public SelectMonsterFrame() {
        initComponents();
        getPartyList();
        this.setSize(780, 500);
        //update_table("select name,attack,defense from monster where char_id=(select char_id from party where user_id="+String.valueOf(userID)+")",partyListTable);
    }

    public SelectMonsterFrame(Party_Data pd, String uid) {
        initComponents();
        userID = uid;
        this.pd = pd;
        getPartyList();
        this.setSize(780, 500);
    }

    private void getPartyList() {
        try {
            partyListTable.setModel(dbakses.getTableData("list_party", "user_id", userID));
            //partyListTable.setModel(dbakses.getTableData("list_party", "user_id", this.userID));
            partyListTable.getColumnModel().getColumn(0).setWidth(0);
            partyListTable.getColumnModel().getColumn(0).setMinWidth(0);
            partyListTable.getColumnModel().getColumn(0).setMaxWidth(0);

            partyListTable.getColumnModel().getColumn(1).setWidth(0);
            partyListTable.getColumnModel().getColumn(1).setMinWidth(0);
            partyListTable.getColumnModel().getColumn(1).setMaxWidth(0);
            for (int i = 3; i < partyListTable.getModel().getColumnCount(); i++) {
                partyListTable.getColumnModel().getColumn(i).setWidth(0);
                partyListTable.getColumnModel().getColumn(i).setMinWidth(0);
                partyListTable.getColumnModel().getColumn(i).setMaxWidth(0);
            }
            selectedParty = new String[partyListTable.getModel().getColumnCount()];
            partyListTable.setRowSelectionInterval(0, 0);
            setItem(0);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error!\n" + e);
        }
    }

    private void setItem(int selRow) {
        nameLabel.setText(partyListTable.getValueAt(selRow, 2).toString());

        int monsterLvl = (int) partyListTable.getValueAt(selRow, 8);
        int baseAtk = (int) partyListTable.getValueAt(selRow, 5);
        int baseDef = (int) partyListTable.getValueAt(selRow, 6);
        int atk = baseAtk + (baseAtk * (monsterLvl / 2));
        int def = baseDef + (baseDef * (monsterLvl / 2));

        int monsterID = (int) partyListTable.getValueAt(selRow, 3);

        lvlLabel.setText(Integer.toString(monsterLvl));
        atkLabel.setText(Integer.toString(atk));
        defLabel.setText(Integer.toString(def));

        s1Label.setText(partyListTable.getValueAt(selRow, 10).toString());
        s1LvlLabel.setText(partyListTable.getValueAt(selRow, 13).toString());

        s2Label.setText(partyListTable.getValueAt(selRow, 15).toString());
        s2LvlLabel.setText(partyListTable.getValueAt(selRow, 18).toString());

        s3Label.setText(partyListTable.getValueAt(selRow, 20).toString());
        s3LvlLabel.setText(partyListTable.getValueAt(selRow, 23).toString());

        for (int i = 0; i < partyListTable.getColumnCount(); i++) {
            selectedParty[i] = partyListTable.getValueAt(selRow, i).toString();
            //System.out.println("selectedParty[" + i + "]" + selectedParty[i]);
        }

        monsterIcon.setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("monsterIcon/" + monsterID + ".png")));
    }

    public void update_table(String sqlStatement, JTable table) {
        dba.setSql(sqlStatement);
        try {
            dba.readandShow();
            table.setModel(dbu.resultSetToTableModel(dba.getRs()));
            table.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
            dba.getCon().close();
        } catch (SQLException sqe) {
            System.out.println(sqe);
        }
    }

    public String[] getSelectedParty() {
        return selectedParty;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        partyListTable = new javax.swing.JTable();
        monsterIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lvlLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        atkLabel = new javax.swing.JLabel();
        defLabel = new javax.swing.JLabel();
        s1Label = new javax.swing.JLabel();
        s2Label = new javax.swing.JLabel();
        s3Label = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        s1LvlLabel = new javax.swing.JLabel();
        s2LvlLabel = new javax.swing.JLabel();
        s3LvlLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Monster");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(750, 450));
        setMinimumSize(new java.awt.Dimension(750, 450));
        setPreferredSize(new java.awt.Dimension(750, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 450));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Monster");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, -1));

        partyListTable.setBackground(new java.awt.Color(0, 0, 0));
        partyListTable.setForeground(new java.awt.Color(255, 255, 255));
        partyListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        partyListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                partyListTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(partyListTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 280, 330));

        monsterIcon.setMaximumSize(new java.awt.Dimension(100, 100));
        monsterIcon.setMinimumSize(new java.awt.Dimension(100, 100));
        monsterIcon.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(monsterIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DEF:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lvl:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Skill lvl:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ATK:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, 10));

        lvlLabel.setForeground(new java.awt.Color(255, 255, 255));
        lvlLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lvlLabel.setText("lvlLabel");
        getContentPane().add(lvlLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 100, -1));

        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nameLabel.setText("nameLabel");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 100, -1));

        atkLabel.setForeground(new java.awt.Color(255, 255, 255));
        atkLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        atkLabel.setText("atkLabel");
        getContentPane().add(atkLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 110, 10));

        defLabel.setForeground(new java.awt.Color(255, 255, 255));
        defLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        defLabel.setText("defLabel");
        getContentPane().add(defLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 180, 110, -1));

        s1Label.setForeground(new java.awt.Color(255, 255, 255));
        s1Label.setText("s1Label");
        getContentPane().add(s1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 120, -1));

        s2Label.setForeground(new java.awt.Color(255, 255, 255));
        s2Label.setText("s2Label");
        getContentPane().add(s2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 120, -1));

        s3Label.setForeground(new java.awt.Color(255, 255, 255));
        s3Label.setText("s3Label");
        getContentPane().add(s3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 120, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Skill:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        s1LvlLabel.setForeground(new java.awt.Color(255, 255, 255));
        s1LvlLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        s1LvlLabel.setText("s1LvlLabel");
        getContentPane().add(s1LvlLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 250, 60, -1));

        s2LvlLabel.setForeground(new java.awt.Color(255, 255, 255));
        s2LvlLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        s2LvlLabel.setText("s2LvlLabel");
        getContentPane().add(s2LvlLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 270, 60, -1));

        s3LvlLabel.setForeground(new java.awt.Color(255, 255, 255));
        s3LvlLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        s3LvlLabel.setText("s3LvlLabel");
        getContentPane().add(s3LvlLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 290, 60, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 90, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Pick!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 90, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/3@300px.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void partyListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_partyListTableMouseClicked
        setItem(partyListTable.getSelectedRow());
    }//GEN-LAST:event_partyListTableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!pd.setParty(selectedParty)) {
            JOptionPane.showMessageDialog(this, "This Monster Already Deployed");
            return;
        }
        this.setVisible(false);

//        try {
//            this.setVisible(false);
//            if (!cp.setParty(selectedParty)) {
//                JOptionPane.showMessageDialog(this, "This Monster Already Deployed");
//                return;
//            }
//
//            plp.panel(plp.p1, plp.getPanel1());
//            plp.p1.setParty2(selectedParty);
//            plp.p1.setVisible(true);
//
//            //cp = new CharPane(plp,7);
//            //cp.setParty2(selectedParty);
////      //  plp.p1=cp;
//            //cp.setVisible(true);        
//            //plp.p1= new CharPane(,7);
//        } catch (NullPointerException ex) {
//            System.out.println(ex);
//        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectMonsterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectMonsterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectMonsterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectMonsterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectMonsterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atkLabel;
    private javax.swing.JLabel defLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lvlLabel;
    private javax.swing.JLabel monsterIcon;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTable partyListTable;
    private javax.swing.JLabel s1Label;
    private javax.swing.JLabel s1LvlLabel;
    private javax.swing.JLabel s2Label;
    private javax.swing.JLabel s2LvlLabel;
    private javax.swing.JLabel s3Label;
    private javax.swing.JLabel s3LvlLabel;
    // End of variables declaration//GEN-END:variables
}
