/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package septian;
import java.awt.Image;
import hilmi.*;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class CharPane extends javax.swing.JPanel {

    /**
     * Creates new form CharPane
     */
    private String[] dataMonster;
    private int monID, slot;
    private ImageIcon icon;
    //private Battle_Campaign_PartySelect_Panel bcp;
    private SelectMonsterFrame smf = new SelectMonsterFrame(); //
    private publicLineupPanel pl;
    private DBAksess dba = new DBAksess();

    /**
     * Creates new form Party_Data
     */
    public CharPane()
    {
        initComponents();
    }
//    public CharPane(Battle_Campaign_PartySelect_Panel bcp, int slot) {
//        initComponents();
//        this.bcp = bcp;
//        this.slot = slot;
//        monsterIcon.setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("monsterIcon/noIcon.png")));
//        monsterName.setText("Not Selected");
//        lvlLabel.setText("-");
//        atkLabel.setText("-");
//        defLabel.setText("-");
//        move1Label.setText("-");
//        move2Label.setText("-");
//        move3Label.setText("-");
//    }
    public CharPane(publicLineupPanel pl, int slot) {
        initComponents();
        this.pl = pl;
        this.slot = slot;
        monsterIcon.setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("monsterIcon/noIcon.png")));
        monsterName.setText("Not Selected");
        lvlLabel.setText("-");
        atkLabel.setText("-");
        defLabel.setText("-");
        move1Label.setText("-");
        move2Label.setText("-");
        move3Label.setText("-");
    }
        
    public boolean setParty(String[] data){
        dataMonster = data;
        //if(data[7].equals(slot)){
        //if(this.setParty(slot, dataMonster[7])){
        //    return false;
        //}
        monsterName.setText(dataMonster[2]);
        lvlLabel.setText(dataMonster[8]);
        String slot = dataMonster[7];
        int monsterLvl = Integer.parseInt(dataMonster[8]);
        int baseAtk = Integer.parseInt(dataMonster[5]);
        int baseDef = Integer.parseInt(dataMonster[6]);
        int atk = baseAtk + (baseAtk * (monsterLvl/2));
        int def = baseDef + (baseDef * (monsterLvl/2));
        atkLabel.setText(Integer.toString(atk));
        defLabel.setText(Integer.toString(def));
        move1Label.setText(dataMonster[10]+" ("+dataMonster[13]+")");
        move2Label.setText(dataMonster[15]+" ("+dataMonster[18]+")");
        move3Label.setText(dataMonster[20]+" ("+dataMonster[23]+")");
        monsterIcon.setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("monsterIcon/"+dataMonster[3]+".png")));
        //return true;
        System.out.println("masuk char pane");
        return false;
    }
    //public void setParty2(String[] data){
    public void setParty2(){
        //dataMonster = data;
        System.out.println("dari Charpane data[0]"+dataMonster[0]);
        System.out.println("dari Charpane data[23]"+dataMonster[23]);
        monsterName.setText(dataMonster[2]);
        lvlLabel.setText(dataMonster[8]);
        int monsterLvl = Integer.parseInt(dataMonster[8]);
        int baseAtk = Integer.parseInt(dataMonster[5]);
        int baseDef = Integer.parseInt(dataMonster[6]);
        int atk = baseAtk + (baseAtk * (monsterLvl/2));
        int def = baseDef + (baseDef * (monsterLvl/2));
        atkLabel.setText(Integer.toString(atk));
        defLabel.setText(Integer.toString(def));
        move1Label.setText(dataMonster[10]+" ("+dataMonster[13]+")");
        move2Label.setText(dataMonster[15]+" ("+dataMonster[18]+")");
        move3Label.setText(dataMonster[20]+" ("+dataMonster[23]+")");
        monsterIcon.setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("monsterIcon/"+dataMonster[3]+".png")));
        System.out.println("masuk char pane");
    }
    
    public String[] getDataMonster(){
        return dataMonster;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        monsterIcon = new javax.swing.JLabel();
        monsterName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lvlLabel = new javax.swing.JLabel();
        atkLabel = new javax.swing.JLabel();
        defLabel = new javax.swing.JLabel();
        Edit = new javax.swing.JButton();
        Del = new javax.swing.JButton();
        move1Label = new javax.swing.JLabel();
        move2Label = new javax.swing.JLabel();
        move3Label = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        monsterIcon.setMaximumSize(new java.awt.Dimension(150, 150));
        monsterIcon.setMinimumSize(new java.awt.Dimension(150, 150));
        monsterIcon.setName(""); // NOI18N
        monsterIcon.setPreferredSize(new java.awt.Dimension(150, 150));
        monsterIcon.setVerifyInputWhenFocusTarget(false);

        monsterName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        monsterName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monsterName.setText("Jeanne D'arc Alter");

        jLabel2.setText("Lvl.");

        jLabel3.setText("ATK.");

        jLabel1.setText("DEF.");

        lvlLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lvlLabel.setText("0");

        atkLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        atkLabel.setText("0");

        defLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        defLabel.setText("0");

        Edit.setText("Edit");
        Edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Del.setText("X");
        Del.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelActionPerformed(evt);
            }
        });

        move1Label.setText("Moves1");

        move2Label.setText("Moves2");

        move3Label.setText("Moves3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(Del, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(move1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(monsterIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lvlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(defLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(monsterName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(move2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(move3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(monsterIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monsterName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lvlLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(atkLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(defLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(move1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(move2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(move3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Del, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        //this.setVisible(false);
        smf.setVisible(true);
    }//GEN-LAST:event_EditActionPerformed

    private void DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelActionPerformed
        monsterIcon.setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("monsterIcon/noIcon.png")));
        monsterName.setText("Not Selected");
        lvlLabel.setText("-");
        atkLabel.setText("-");
        defLabel.setText("-");
        move1Label.setText("-");
        move2Label.setText("-");
        move3Label.setText("-");
        dataMonster = null;
        //.resetSlot(slot);
    }//GEN-LAST:event_DelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Del;
    private javax.swing.JButton Edit;
    private javax.swing.JLabel atkLabel;
    private javax.swing.JLabel defLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lvlLabel;
    private javax.swing.JLabel monsterIcon;
    private javax.swing.JLabel monsterName;
    private javax.swing.JLabel move1Label;
    private javax.swing.JLabel move2Label;
    private javax.swing.JLabel move3Label;
    // End of variables declaration//GEN-END:variables
}
