/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iskandar;
import com.ish.monsterspirit.MainDashBoard;
import iskandar.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author delimiter_
 */
public class index extends javax.swing.JPanel {

    private MainDashBoard mdb;
    private register rgs;
    private login lgn;
    /**
     * Creates new form index
     */
    
 MainDashBoard mf;
    public index() {
     initComponents();      
    }
    public index(MainDashBoard mdb) {
     initComponents();
     this.mdb=mdb;
//     rgs = new register(this);
//        add(rgs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
//        rgs.setVisible(false);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(763, 516));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MONSTER SPIRIT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 220, 61));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 22, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 180, 60));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTER");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REGISTER");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 180, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        jPanel1.setBackground(Color.GRAY);
////        mf.register();
////        mf.setVisible(true);
////        this.setVisible(false);
//        //this.setVisible(false);
//        
////        lgn = new login(this);
////        this.setSize(763, 461);
////        add(lgn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
//        this.setVisible(false);
//        //this.mdb.setSize(763, 461);
//        lgn.setVisible(true);
        //this.setSize(763, 461);
        this.jPanel1.setVisible(false);
        this.jPanel3.setVisible(false);
        this.jLabel1.setVisible(false);
        lgn = new login(this);
        add(lgn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        lgn.setVisible(true);
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        jPanel1.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        jPanel3.setBackground(Color.GRAY);
////        this.setSize(691, 516);
////        //this.setVisible(false);
////        this.remove(jPanel3);
////        this.remove(jPanel1);
////        this.remove(jLabel1);
////        rgs = new register(this);
////        add(rgs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
//        this.setVisible(false);
//        //this.mdb.setSize(691, 516);
//        rgs.setVisible(true);
        //this.setSize(691, 516);
        this.jPanel1.setVisible(false);
        this.jPanel3.setVisible(false);
        this.jLabel1.setVisible(false);
        rgs = new register(this);
        add(rgs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));
        rgs.setVisible(true);
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
       jPanel3.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel3MouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
