/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iskandar;

import com.ish.monsterspirit.DBAksess;
import com.ish.monsterspirit.MainDashBoard;
import com.ish.monsterspirit.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author delimiter_
 */
public class register extends javax.swing.JPanel {

    /**
     * Creates new form register
     */
//    Connection con;
//    Statement stat;
//    ResultSet rs;
//    String sql;
    MainDashBoard mdf;
    private index idx;
    public register(MainDashBoard mdf) {
        initComponents();
            //this.mdf=mdf;
            //this.mdf.setSize(this.getSize());
         Money1.setEditable(false);
         CampaignLevel1.setEditable(false);
    }
    public register(index idx) {
        initComponents();
            this.idx=idx;
         Money1.setEditable(false);
         CampaignLevel1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnLogin1 = new java.awt.Button();
        password1 = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Money = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        CampaignLevel = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnLogin = new java.awt.Button();
        password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        username1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Money1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        CampaignLevel1 = new javax.swing.JTextField();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnLogin1.setBackground(new java.awt.Color(102, 51, 255));
        btnLogin1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin1.setLabel("Register");
        btnLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogin1MousePressed(evt);
            }
        });
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        password1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        password1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        password1.setText("Password");
        password1.setBorder(null);
        password1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password1FocusLost(evt);
            }
        });
        password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password1ActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        username.setText("Username");
        username.setBorder(null);
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setText("REGISTER GAME");

        Money.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Money.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Money.setText("Money");
        Money.setBorder(null);
        Money.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MoneyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MoneyFocusLost(evt);
            }
        });
        Money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyActionPerformed(evt);
            }
        });
        Money.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MoneyKeyTyped(evt);
            }
        });

        CampaignLevel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampaignLevel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CampaignLevel.setText("Campaign Level");
        CampaignLevel.setBorder(null);
        CampaignLevel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampaignLevelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CampaignLevelFocusLost(evt);
            }
        });
        CampaignLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampaignLevelActionPerformed(evt);
            }
        });
        CampaignLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampaignLevelKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CampaignLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator7)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator6)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Money, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(CampaignLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Money, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(763, 516));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(102, 51, 255));
        btnLogin.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setLabel("Register");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 336, 334, 35));

        password.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        password.setText("Password");
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 144, 329, 41));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 191, 340, -1));

        username1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        username1.setText("Username");
        username1.setBorder(null);
        username1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username1FocusLost(evt);
            }
        });
        username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username1ActionPerformed(evt);
            }
        });
        username1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                username1KeyTyped(evt);
            }
        });
        jPanel2.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 90, 321, 41));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setText("REGISTER GAME");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 35, -1, -1));

        Money1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Money1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Money1.setText("Money");
        Money1.setBorder(null);
        Money1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Money1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Money1FocusLost(evt);
            }
        });
        Money1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Money1ActionPerformed(evt);
            }
        });
        Money1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Money1KeyTyped(evt);
            }
        });
        jPanel2.add(Money1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 250, 320, 41));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 242, 340, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 137, 340, 1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 305, 340, -1));

        CampaignLevel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampaignLevel1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CampaignLevel1.setText("Campaign Level");
        CampaignLevel1.setBorder(null);
        CampaignLevel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampaignLevel1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CampaignLevel1FocusLost(evt);
            }
        });
        CampaignLevel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampaignLevel1ActionPerformed(evt);
            }
        });
        CampaignLevel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampaignLevel1KeyTyped(evt);
            }
        });
        jPanel2.add(CampaignLevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 195, 319, 41));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 470, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogin1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogin1MousePressed

    }//GEN-LAST:event_btnLogin1MousePressed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
       
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void password1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password1FocusGained
        // TODO add your handling code here:
        if(password.getText().equals("Password")){
            password.setText("");
        }
    }//GEN-LAST:event_password1FocusGained

    private void password1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password1FocusLost
        if(password.getText().equals("")){
            password.setText("Password");
        }
    }//GEN-LAST:event_password1FocusLost

    private void password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password1ActionPerformed

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        if(username.getText().equals("Email")){
            username.setText("");
        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        if(username.getText().equals("")){
            username.setText("Email");
        }
    }//GEN-LAST:event_usernameFocusLost

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameKeyTyped

    private void MoneyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MoneyFocusGained
        if(Money.getText().equals("Nickname")){
            Money.setText("");
        }
    }//GEN-LAST:event_MoneyFocusGained

    private void MoneyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MoneyFocusLost
        if(Money.getText().equals("")){
            Money.setText("Nickname");
        }
    }//GEN-LAST:event_MoneyFocusLost

    private void MoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoneyActionPerformed

    private void MoneyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MoneyKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_MoneyKeyTyped

    private void CampaignLevelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampaignLevelFocusGained
        if(CampaignLevel.getText().equals("")){
            CampaignLevel.setText("Full Name");
        }
    }//GEN-LAST:event_CampaignLevelFocusGained

    private void CampaignLevelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampaignLevelFocusLost
        if(CampaignLevel.getText().equals("Full Name")){
            CampaignLevel.setText("");
        }
    }//GEN-LAST:event_CampaignLevelFocusLost

    private void CampaignLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampaignLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampaignLevelActionPerformed

    private void CampaignLevelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampaignLevelKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CampaignLevelKeyTyped
     public DBAksess db;
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        db=new DBAksess();
        db.setSql("select * from player");
        
        if(!username1.getText().equals("")&&!password.getText().equals("")&&!CampaignLevel1.getText().equals("")&&!Money1.getText().equals("")){
        try
        {
            db.setSql("INSERT INTO player (user_id,username,password,CampaignLevel,Money) VALUES ("+username1.getText()+",'"+username1.getText()+"','"+password.getText()+"',0,0)");
            db.write();
            JOptionPane.showMessageDialog(null, "Succesfully");
            this.setVisible(false);
            mdf = new MainDashBoard();
            this.mdf.setVisible(true);
        }
        catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
            ex.getCause();
        }
    }else{
        JOptionPane.showMessageDialog(null, "Harus terisi semua.");
    }
   
    }//GEN-LAST:event_btnLoginActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        if(password.getText().equals("Password")){
            password.setText("");
        }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if(password.getText().equals("")){
            password.setText("Password");
        }
    }//GEN-LAST:event_passwordFocusLost

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void username1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username1FocusGained
        if(username1.getText().equals("Username")){
            username1.setText("");
        }
    }//GEN-LAST:event_username1FocusGained

    private void username1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username1FocusLost
        if(username1.getText().equals("")){
            username1.setText("Username");
        }
    }//GEN-LAST:event_username1FocusLost

    private void username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username1ActionPerformed

    private void username1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_username1KeyTyped

    private void Money1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Money1FocusGained
        if(Money.getText().equals("Nickname")){
            Money.setText("");
        }
    }//GEN-LAST:event_Money1FocusGained

    private void Money1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Money1FocusLost
        if(Money.getText().equals("")){
            Money.setText("Nickname");
        }
    }//GEN-LAST:event_Money1FocusLost

    private void Money1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Money1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Money1ActionPerformed

    private void Money1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Money1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Money1KeyTyped

    private void CampaignLevel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampaignLevel1FocusGained
        if(CampaignLevel.getText().equals("")){
            CampaignLevel.setText("Full Name");
        }
    }//GEN-LAST:event_CampaignLevel1FocusGained

    private void CampaignLevel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampaignLevel1FocusLost
        if(CampaignLevel.getText().equals("Full Name")){
            CampaignLevel.setText("");
        }
    }//GEN-LAST:event_CampaignLevel1FocusLost

    private void CampaignLevel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampaignLevel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampaignLevel1ActionPerformed

    private void CampaignLevel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampaignLevel1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CampaignLevel1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampaignLevel;
    private javax.swing.JTextField CampaignLevel1;
    private javax.swing.JTextField Money;
    private javax.swing.JTextField Money1;
    private java.awt.Button btnLogin;
    private java.awt.Button btnLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password1;
    private javax.swing.JTextField username;
    private javax.swing.JTextField username1;
    // End of variables declaration//GEN-END:variables
}
