/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ricylebin;

import septian.*;
import com.ish.monsterspirit.ReadTable;
import hilmi.DBAksess;
import java.awt.Color;
import java.awt.Font;
import static java.awt.image.ImageObserver.ERROR;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class upgradePartyPanel extends javax.swing.JPanel {

    /**
     * Creates new form scoutPanel
     */
    public upgradePartyPanel() {
        initComponents();
        this.gold.setMaximum(maxMoney);
        this.gold.setMinimum(0);
        this.gold.setValue(money);
        this.gold.setString(money+"/"+maxMoney+" Gold");
        this.gold.setForeground(Color.black);
        this.gold.setBackground(Color.yellow);
        v.display_table(TabelGambarCharacter,"select * from list_party2 where user_id = "+String.valueOf(UID));
        testing[0]=TabelGambarCharacter.getRowCount()-1;
        setatribute(testing);
    }
    private int UID=1;
    private int[] testing = new int[1];
    
    private final Integer maxMoney = 10000000; 
    private Integer money =1000000;
    private Integer reqvalue=4000;
    private ReadTable v = new ReadTable();
    private DBAksess dba = new DBAksess();
    public Object[][] selectedParty;
    
    public void loadpanel()
    {
        v.display_table(TabelGambarCharacter,"select * from list_party2 where user_id = "+String.valueOf(UID));
        setatribute(testing);
    }
    
    private Integer reqlvlup(Integer lvl, Integer reqvalue)
    {
        reqvalue=((((lvl+1)*1000)+reqvalue)*(lvl+1)-(lvl*1000));
        return reqvalue;
    }
    private void setatribute(int[] selected)
    {
        int x[] = selected;//TabelGambarCharacter.getSelectedRows();
        selectedParty = v.getSelectedParty();
        for(int i=0;i<x.length;i++)
        {
        name_label.setText(v.getSelectedParty()[x[i]][2].toString());    
        int monsterLvl = Integer.parseInt(v.getSelectedParty()[x[i]][9].toString());
        int baseAtk = Integer.parseInt(v.getSelectedParty()[x[i]][5].toString());
        int baseDef = Integer.parseInt(v.getSelectedParty()[x[i]][6].toString());
        int atk = baseAtk + (baseAtk * (monsterLvl/2));
        int def = baseDef + (baseDef * (monsterLvl/2));
        
        int monsterID = Integer.parseInt(v.getSelectedParty()[x[i]][3].toString());
        
        lvl_label.setText(Integer.toString(monsterLvl));
        atk_label.setText(Integer.toString(atk));
        def_label.setText(Integer.toString(def));
        
        skill1_label.setText(v.getSelectedParty()[x[i]][10].toString());//(TabelGambarCharacter.getValueAt(selRow, 10).toString());
        //s1LvlLabel.setText(TabelGambarCharacter.getValueAt(selRow, 13).toString());
        
        skill2_label.setText(v.getSelectedParty()[x[i]][15].toString());//(TabelGambarCharacter.getValueAt(selRow, 15).toString());
        //s2LvlLabel.setText(TabelGambarCharacter.getValueAt(selRow, 18).toString());
        
        skill3_label.setText(v.getSelectedParty()[x[i]][20].toString());//(TabelGambarCharacter.getValueAt(selRow, 20).toString());
        //s3LvlLabel.setText(TabelGambarCharacter.getValueAt(selRow, 23).toString());
        
        Image_monster.setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("monsterIcon/"+monsterID+".png")));
            System.out.println(v.getSelectedParty()[x[i]][4]);
        }
        reqvalue_label.setText(String.valueOf(reqlvlup(Integer.parseInt(lvl_label.getText()),reqvalue)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelGambarCharacter = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        LvlupBtn = new javax.swing.JButton();
        UpgradeBtn = new javax.swing.JButton();
        gold = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        lvl_label = new javax.swing.JLabel();
        atk_label = new javax.swing.JLabel();
        def_label = new javax.swing.JLabel();
        skill1_label = new javax.swing.JLabel();
        skill2_label = new javax.swing.JLabel();
        skill3_label = new javax.swing.JLabel();
        skill4_label = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Image_monster = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        reqvalue_label = new javax.swing.JLabel();
        skill_list = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(955, 515));
        setPreferredSize(new java.awt.Dimension(955, 515));

        jButton1.setText("<--");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        TabelGambarCharacter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelGambarCharacter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelGambarCharacterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelGambarCharacter);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        LvlupBtn.setText("LVL UP");
        LvlupBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LvlupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LvlupBtnActionPerformed(evt);
            }
        });

        UpgradeBtn.setText("SKILL UPGRADE");
        UpgradeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UpgradeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpgradeBtnActionPerformed(evt);
            }
        });

        gold.setBackground(new java.awt.Color(255, 255, 0));
        gold.setFont(new java.awt.Font("MV Boli", 1, 8)); // NOI18N
        gold.setMaximum(0);
        gold.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gold.setMinimumSize(new java.awt.Dimension(10, 18));
        gold.setPreferredSize(new java.awt.Dimension(146, 20));
        gold.setString("0 Gold");
        gold.setStringPainted(true);

        jLabel9.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PARTY");

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        name_label.setBackground(new java.awt.Color(204, 204, 204));
        name_label.setForeground(new java.awt.Color(255, 255, 255));
        name_label.setText("Name :");
        name_label.setPreferredSize(new java.awt.Dimension(35, 34));

        lvl_label.setBackground(new java.awt.Color(204, 204, 204));
        lvl_label.setForeground(new java.awt.Color(255, 255, 255));
        lvl_label.setText("Lvl :");
        lvl_label.setPreferredSize(new java.awt.Dimension(35, 34));

        atk_label.setBackground(new java.awt.Color(204, 204, 204));
        atk_label.setForeground(new java.awt.Color(255, 255, 255));
        atk_label.setText("ATK :");
        atk_label.setPreferredSize(new java.awt.Dimension(35, 34));

        def_label.setBackground(new java.awt.Color(204, 204, 204));
        def_label.setForeground(new java.awt.Color(255, 255, 255));
        def_label.setText("DEF :");
        def_label.setPreferredSize(new java.awt.Dimension(35, 34));

        skill1_label.setBackground(new java.awt.Color(204, 204, 204));
        skill1_label.setForeground(new java.awt.Color(255, 255, 255));
        skill1_label.setText("Skill 1 :");
        skill1_label.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ability", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        skill1_label.setPreferredSize(new java.awt.Dimension(35, 34));

        skill2_label.setBackground(new java.awt.Color(204, 204, 204));
        skill2_label.setForeground(new java.awt.Color(255, 255, 255));
        skill2_label.setText("Skill 2 :");
        skill2_label.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ability", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        skill2_label.setPreferredSize(new java.awt.Dimension(35, 34));

        skill3_label.setBackground(new java.awt.Color(204, 204, 204));
        skill3_label.setForeground(new java.awt.Color(255, 255, 255));
        skill3_label.setText("Skill 3 :");
        skill3_label.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ability", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        skill3_label.setPreferredSize(new java.awt.Dimension(35, 34));

        skill4_label.setBackground(new java.awt.Color(204, 204, 204));
        skill4_label.setForeground(new java.awt.Color(255, 255, 255));
        skill4_label.setText("Skill 4 :");
        skill4_label.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ability", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        skill4_label.setPreferredSize(new java.awt.Dimension(35, 34));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ATK :");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lvl :");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Name :");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DEF :");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Skill 1 :");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Skill 2 :");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Skill 3 :");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Skill 4 :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(3, 3, 3)
                        .addComponent(atk_label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(def_label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(skill2_label, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(name_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lvl_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(skill1_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(skill3_label, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(skill4_label, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addComponent(jSeparator3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvl_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atk_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skill1_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skill2_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skill3_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skill4_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        jButton2.setText("-->");

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 8));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Image_monster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image_monster.setText("jLabel1");
        Image_monster.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel1.setText("Money lvl UP :");

        reqvalue_label.setText("0");

        skill_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(181, 181, 181)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UpgradeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LvlupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(gold, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(skill_list, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reqvalue_label, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Image_monster, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 78, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(reqvalue_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Image_monster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(skill_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UpgradeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LvlupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LvlupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LvlupBtnActionPerformed
        System.out.println(reqlvlup(Integer.parseInt(lvl_label.getText()),reqvalue)+" Money :"+money);
        if(money>=reqlvlup(Integer.parseInt(lvl_label.getText()),reqvalue))
        {
            try {
                money -=reqlvlup(Integer.parseInt(lvl_label.getText()),reqvalue);
                this.gold.setString(money+"/"+maxMoney+" Gold");//(currentHP+"/"+maximumHP+" HP");
                this.gold.setValue(money);
                dba.setSql("UPDATE party SET level_user = level_user + 1 WHERE user_id = "+String.valueOf(UID)+" AND char_name ='"+name_label.getText()+"'");
                dba.write();
                JOptionPane.showMessageDialog(this,"mosnter upgraded to Lvl : "+(Integer.parseInt(lvl_label.getText())+1));
                //setatribute(testing);
                loadpanel();
            } catch (SQLException ex) {
                Logger.getLogger(upgradePartyPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else
        {
            JOptionPane.showMessageDialog(this,"Haven't enough of gold");
        }
    }//GEN-LAST:event_LvlupBtnActionPerformed

    private void TabelGambarCharacterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelGambarCharacterMouseClicked
        testing=TabelGambarCharacter.getSelectedRows();
        setatribute(TabelGambarCharacter.getSelectedRows());
    }//GEN-LAST:event_TabelGambarCharacterMouseClicked

    private void UpgradeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpgradeBtnActionPerformed
        if((!skill_list.getSelectedItem().equals("")||!skill_list.getSelectedItem().equals(null))&&Integer.parseInt(lvl_label.getText())>=4)
        {
            if(money>=reqlvlup(Integer.parseInt(lvl_label.getText()),reqvalue))
            {
                try{
                    money -=reqlvlup(Integer.parseInt(lvl_label.getText()),reqvalue);
                    this.gold.setString(money+"/"+maxMoney+" Gold");//(currentHP+"/"+maximumHP+" HP");
                    this.gold.setValue(money);
                    dba.setSql("UPDATE party SET UpgradeSkill_"+skill_list.getSelectedItem()+" = UpgradeSkill_"+skill_list.getSelectedItem()+" + 1 WHERE user_id = "+String.valueOf(UID)+" AND char_name ='"+name_label.getText()+"'");
                    dba.write();
                }catch(SQLException ex)
                {
                    Logger.getLogger(upgradePartyPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else
            {
                JOptionPane.showMessageDialog(this,"Haven't enough of gold");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Your requierment level is'nt enough !");
        }
        JOptionPane.showMessageDialog(this,"mosnter skill"+skill_list.getSelectedItem()+" upgraded to Lvl : "+(Integer.parseInt(skill_list.getSelectedItem().toString())+1));
        loadpanel();
    }//GEN-LAST:event_UpgradeBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image_monster;
    private javax.swing.JButton LvlupBtn;
    private javax.swing.JTable TabelGambarCharacter;
    private javax.swing.JButton UpgradeBtn;
    private javax.swing.JLabel atk_label;
    private javax.swing.JLabel def_label;
    private javax.swing.JProgressBar gold;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lvl_label;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel reqvalue_label;
    private javax.swing.JLabel skill1_label;
    private javax.swing.JLabel skill2_label;
    private javax.swing.JLabel skill3_label;
    private javax.swing.JLabel skill4_label;
    private javax.swing.JComboBox<String> skill_list;
    // End of variables declaration//GEN-END:variables
}
